# Generated by Django 4.0.2 on 2022-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
