# Generated by Django 4.0.2 on 2022-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address_profile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='year_of_experinse',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
