# Generated by Django 4.0.2 on 2022-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_about_profile_year_of_experinse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_of_experinse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
